### PR TITLE
validate that jdbc level timeouts are used in both JDOQL & SQL queries

### PR DESCRIPTION
**Pull request by pktxu**
tests for datanucleus/datanucleus-rdbms#44 

Tested against PostgreSQL, couldn't figure out how to cater for other RDBMSs nor how to generate the equivalent of `SELECT FOR UPDATE` for them.

### CODE REVIEW

**Comment by andyjefferson** [comment]
Sorry, cannot apply a test that 
a). spews exceptions out onto the console with Maven (PostgreSQL)
Exception in thread "Thread-4" javax.jdo.JDOException: Exception thrown when executing query : SELECT 'org.jpox.samples.models.company.Office' AS nucleus_type,a0."date",a0.description,a0.floor,a0.roomname,a0.office_id FROM office a0 WHERE a0.description = 'QueryTimeout-foo' FOR UPDATE
        at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:677)
        at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:392)
        at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:217)
        at org.datanucleus.tests.QueryTimeoutTest$ImpatientSearcher.run(QueryTimeoutTest.java:235)
        at java.lang.Thread.run(Thread.java:745)
NestedThrowablesStackTrace:
org.postgresql.util.PSQLException: ERROR: canceling statement due to user request
  Where: while locking tuple (0,3) in relation "office"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:305)
        at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:94)
        at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:94)
        at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeQuery(ParamLoggingPreparedStatement.java:375)
        at org.datanucleus.store.rdbms.SQLController.executeStatementQuery(SQLController.java:552)
        at org.datanucleus.store.rdbms.query.JDOQLQuery.performExecute(JDOQLQuery.java:618)
        at org.datanucleus.store.query.Query.executeQuery(Query.java:1922)
        at org.datanucleus.store.query.Query.executeWithArray(Query.java:1811)
        at org.datanucleus.store.query.Query.execute(Query.java:1793)
        at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:375)
        at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:217)
        at org.datanucleus.tests.QueryTimeoutTest$ImpatientSearcher.run(QueryTimeoutTest.java:235)
        at java.lang.Thread.run(Thread.java:745)

b). doesn't work with other datastores (tried on H2). If some datastore doesn't support timeouts then the test should check with the the StoreManager.supportedOptions and return if that feature is not supported.

**Comment by andyjefferson** [comment]
There is no such property "javax.jdo.option.Datastore.Timeout". It is "javax.jdo.option.DatastoreTimeout". Fails on H2 and others.

**Comment by pktxu** [comment]
Andy,

Have you had a change to review this?

* Andy Jefferson <notifications@github.com> [20160425 20:06]:
> There is no such property "javax.jdo.option.Datastore.Timeout". It is "javax.jdo.option.DatastoreTimeout". Fails on H2 and others.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/datanucleus/tests/pull/6#issuecomment-214446240

-- 
pica

**Comment by andyjefferson** [comment]
I reviewed it some time ago. You seem to have changed one use of that parameter, but not the other. Also I said "fails on H2 and others". Are all of those addressed now?

**Comment by andyjefferson** [comment]
No update on this? If nothing changes soon I will close it, since no point in incomplete requests sitting here

**Comment by pktxu** [comment]
* Andy Jefferson <notifications@github.com> [20160726 08:24]:
> No update on this? If nothing changes soon I will close it, since no
> point in incomplete requests sitting here

Will have to wait until september. I recall not being able to find how
to adapt the serialized read syntax to different RDBMS's (the test
assumes "SELECT FOR UPDATE"), suggestions?

**Comment by andyjefferson** [comment]
You could consider restricting a test to particular datastores using @Datastore({POSTGRESQL}) for example like is done for https://github.com/datanucleus/tests/blob/master/jdo/geospatial/src/test/org/datanucleus/tests/JtsGeometrySpatialTest.java

**Comment by pktxu** [comment]
Done as suggested.

Might also be done via DatastoreAdapter.LOCK_OPTION_PLACED_AFTER_FROM,
but couldn't get to it from the test.

* Andy Jefferson <notifications@github.com> [20160818 12:31]:
> You could consider restricting a test to particular datastores using @Datastore({POSTGRESQL}) for example like is done for https://github.com/datanucleus/tests/blob/master/jdo/geospatial/src/test/org/datanucleus/tests/JtsGeometrySpatialTest.java
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/datanucleus/tests/pull/6#issuecomment-240688184

-- 
pica

**Pull request merged**
